controller_list:
  - name: fake_arm_controller
    joints:
      - arm_base_arm_lr_joint
      - arm_lr_arm_ud1_joint
      - arm_ud1_arm_ud2_joint
      - arm_ud2_arm_ud3_joint
      - arm_ud3_arm_wrist_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: init